source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
# gem 'kbase-github-pages-theme', git: 'https://github.com/kbaseIncubator/kbase-github-pages-theme'
gem 'kbase-github-pages-theme', path: '../../kbase-github-pages-theme'